#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hanyang.Droid.Resource", IsApplication=true)]

namespace Hanyang.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int animation = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int arrow_left = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int arrow_right = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int arrow_up = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int coronamap = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int error = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int hanyang = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int hanyang_homepage = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int hanyang_news = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int home = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int icon = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int info = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int more = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int my_progress_bar = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int notice = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int open_source = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int profile = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int refresh = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int schedule = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int school_newsletter = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int self_diagnosis = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int setting = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int splash_screen_bg = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int splash_screen_logo = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int xamarin_logo = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int xamarin_text_logo = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int background = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int progress = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int progressBar = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int sliding_tabs = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int toolbar = 2130903044;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int SplashScreen = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Tabbar = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Toolbar = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F060000
			public const int notification = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppCompatDialogStyle = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int MainTheme = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int MainTheme_Base = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
